<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b7901f41-ffc4-42a2-9377-1951af5dd9dc</elementGuidId>
    <imagePath></imagePath>
    <name>com_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/com-1password-button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>