<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f5cbc8f1-68dd-4c4c-8f7a-c634cffb5931</elementGuidId>
    <imagePath></imagePath>
    <name>p_object_32</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/main[1]/div[2]/div[3]/div[2]/div[1]/p[27]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>