<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2d53ddb4-46cd-45e9-9faf-aaa58a65cc3f</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_142</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//html/div[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>