<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7e160092-8bf0-41e3-915c-a92d57baf4bf</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_161</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>