<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6df97191-9296-4f0b-9dc9-a3119a105988</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_11</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/div[1]/div[2]/div[4]/div[1]/div[2]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>