<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>12f56817-e2c2-426c-9ec5-b3382b08531b</elementGuidId>
    <imagePath></imagePath>
    <name>strong_object_13</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[2]/div[3]/div[2]/div[1]/h3[1]/strong[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>