<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7cc00e35-b8f1-4a90-95a0-50d7b2e1ddd4</elementGuidId>
    <imagePath></imagePath>
    <name>h3_object_29</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[2]/div[3]/div[2]/div[1]/div[2]/h3[7]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>